version: "1"
services:
  jupyter:
    container_name: bdv_notebook
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./app/notebooks:/home/jovyan/work
      - ./app/data:/home/jovyan/data
      - ./app/.models:/home/jovyan/.models